apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jupyter-crypto
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jupyter-crypto
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jupyter-crypto
    spec:
      containers:
      - name: jupyter
        image: securitycast/jupyter_crypto@sha256:6beccb2382301aca1fdf1ffe82d403473b6f6e41cbd8a2f16dc8de3bb2bfabbc
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-crypto
spec:
  selector: 
    app.kubernetes.io/name: jupyter-crypto
  ports:
    - protocol: TCP
      port: 8888
